// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcvYnX_jtmnYQGBRWULV0UpPgxYGGgHsk',
    appId: '1:532195209657:android:72aca62a42ef0780950668',
    messagingSenderId: '532195209657',
    projectId: 'sharemedia-820ca',
    databaseURL: 'https://sharemedia-820ca-default-rtdb.firebaseio.com',
    storageBucket: 'sharemedia-820ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5u_NytveUgO8hiHt0OP73XZqf_tuNNU',
    appId: '1:532195209657:ios:a38173ad244f2c6e950668',
    messagingSenderId: '532195209657',
    projectId: 'sharemedia-820ca',
    databaseURL: 'https://sharemedia-820ca-default-rtdb.firebaseio.com',
    storageBucket: 'sharemedia-820ca.appspot.com',
    androidClientId: '532195209657-9it5csqoq8vsem083hcfp4pc6qbh16ga.apps.googleusercontent.com',
    iosClientId: '532195209657-tg9c51i8kt5p83aqm6iao6ed4qdcejjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.happ',
  );
}
